configuration:  
  projectName: config-client - DEV
server:
  port: 8000
host:
<<<<<<< HEAD
  ip: 192.168.1.23
=======
  ip: localhost
>>>>>>> branch 'master' of https://github.com/WalmirRocha/config-repo.git
